version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: "minio_access_key"
      MINIO_SECRET_KEY: "minio_secret_key"
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9090"
    networks:
      - my-network

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - minio
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
